define({ "api": [
  {
    "type": "post",
    "url": "/admin/login",
    "title": "Admin Login",
    "description": "<p>This is used for login into different user types(admin/sales/hr)</p>",
    "group": "admin",
    "version": "0.1.0",
    "parameter": {
      "fields": {
        "Parameter": [
          {
            "group": "Parameter",
            "type": "String",
            "optional": false,
            "field": "accountToken",
            "description": "<p>This is the account token generated by web/token endpoint</p>"
          }
        ]
      },
      "examples": [
        {
          "title": "Request-Example:",
          "content": "{\n        accountToken:<>\n        email:admin@therapyondemand.io\n        password:Admin@12345\n}",
          "type": "type"
        }
      ]
    },
    "success": {
      "fields": {
        "200": [
          {
            "group": "200",
            "type": "String",
            "optional": false,
            "field": "image",
            "description": "<p>Base64 Image</p>"
          }
        ]
      },
      "examples": [
        {
          "title": "Success-Response:",
          "content": "{\n       data:{\n            sessionToken:<>\n            role:\"admin\",\n            fullName:<>\n            firstName:<>\n            lastName:<>\n            email:<>\n            image:<>\n            phone:<>\n        }\n        message:\"\"\n}",
          "type": "type"
        }
      ]
    },
    "filename": "docs/admin.js",
    "groupTitle": "admin",
    "name": "PostAdminLogin"
  },
  {
    "type": "post",
    "url": "/get/profile",
    "title": "My Profile Details",
    "description": "<p>This Api is used to get the logged in users profile details</p>",
    "group": "universal",
    "version": "0.1.0",
    "parameter": {
      "fields": {
        "Parameter": [
          {
            "group": "Parameter",
            "type": "String",
            "optional": false,
            "field": "accountToken",
            "description": "<p>This is the account token generated by web/token endpoint</p>"
          },
          {
            "group": "Parameter",
            "type": "String",
            "optional": false,
            "field": "sessionToken",
            "description": "<p>This is the token which u=you get while calling the admin/login apis</p>"
          }
        ]
      },
      "examples": [
        {
          "title": "Request-Example:",
          "content": "{\n        accountToken:<>\n        sessionToken:<>\n}",
          "type": "type"
        }
      ]
    },
    "success": {
      "fields": {
        "200": [
          {
            "group": "200",
            "type": "String",
            "optional": false,
            "field": "role",
            "description": "<p>Role of the user (admin/hr/sales)</p>"
          }
        ]
      },
      "examples": [
        {
          "title": "Success-Response:",
          "content": "{\n        data:{\n            role:<>\n            fullName:<>\n            firstName:<>\n            lastName:<>\n            email:<>\n            image:<>\n            phone:<>\n        }\n        message:\"Successfully fetched the profile details\"\n}",
          "type": "type"
        }
      ]
    },
    "filename": "docs/admin.js",
    "groupTitle": "universal",
    "name": "PostGetProfile"
  }
] });
